### ISSUE TITLE
Questions about this plugin tuning TDP

### ISSUE THREAD

**Issue by 01chenyitian** [ShadowBlip/HandyPT#10]
First of all, many thanks to the developers for designing this plugin, it helps a lot. My device is 4800U. When I set TDP to 15 in the plugin, it was about 10W; When I set TDP to 20, it was actually around 15W. I don't know why, so I ask.
Then I wanted to see if there was a TDP for different games.
Finally, thank you again!

**Comment by pastaq** [comment]
I'll need a bit more info about where you're seeing that. Is there an issue with the slider or are you reading the value from another tool?

As for the second question, I've not yet incorporated persistence or per game profiles. That's on the to-do list though.

**Comment by 01chenyitian** [comment]
Hello! The main thing I'm confused about is that the TDP set by HandyPT plugin slider is different from the CPU power display that SteamOS comes with. For example, the slider is set to 15, but the actual CPU power consumption is displayed as 10W.
Thank you for your answer!

**Comment by pastaq** [comment]
> Hello! The main thing I'm confused about is that the TDP set by HandyPT plugin slider is different from the CPU power display that SteamOS comes with. For example, the slider is set to 15, but the actual CPU power consumption is displayed as 10W. Thank you for your answer!

Ah, yes that makes sense. So the TDP slider is for the overall SoC package, including the CPU and GPU chips. You may notice if you disable CPU boosting the TDP of the CPU goes down, giving more power to the GPU. Enabled it will do the opposite. This can be useful for games limited by the GPU where the CPU is mostly at idle. Since they are all on a single chip they can't be set indivudually unfortunately, so I have a few tweaks in there to try and limit the CPU power if needed, if only by a couple watts. 

If you look at the bottom of HandyPT you will see a Battery Draw value. This is the total power being used by the system overall (when not plugged in, then it will be 0). That includes the SSD, motherboard, speakers, wifi, bluetooth, and anything else your system is running form battery. You can use this to tune max performance over time to get the best battery life while mobile.

**Comment by 01chenyitian** [comment]
Thank you for your answer! ~
