### ISSUE TITLE
Aya Neo 2021, TDP shows NaN after interaction

### ISSUE THREAD

**Issue by ch3vr0n5** [ShadowBlip/HandyPT#3]
After installing Crankshaft and HandyPT the plugin shows up as expected. It shows AYA NEO 2021 at the top and is set to a max of 15 W on the TDP slider. From there things don't work as expected. 

I am unable to interact with the plugin via controller but I can with the touch screen. 
The touch screen targets are wildly off and I have to shoot left of the slider to actually make it move. 
Once I am able to move the slider the TDP shows NaN and it doesn't appear to effect the TDP at all.
Using a mouse, the nearest slider to the mouse cursor seems to lock to to cursor and constantly moves. You can't click on a slider, adjust it, and place it. It just constantly moves up and down along with the mouse horizontal movements.

Aya Neo 2021
HoloISO latest stable (20220711 - Update 2)

**Comment by pastaq** [comment]
Thank you for your report. 
1.) The slider location will be addressed in v0.2.0. This was due to a difference in the HoloISO gamescope-session and the ChimeraOS gamescope-session. Now that they are at parity I have reworked how this interaction occurs.
2.) Another user identified the 4500U issue and submitted PR #1 which I have merged. It will also release in v.0.2.0
3.) I'm working on the controller support. Crankshaft v0.19.0 enabled support for this, but it has some issues with the built-in elements that steam uses. I'm working with the developer for a solution that is more universal. I have no current ETA for this.

Expect v0.2.0 to release quickly after ChimeraOS v34. Releasing it earlier than that will break it for everyone using the older gamescope-session.
